### ISSUE TITLE
libE redirects root logger output on import

### ISSUE THREAD

**Issue by rsln-s** [Libensemble/libensemble#105]
This line redirects root logger to `ensemble.log`:

`logging.basicConfig(filename='ensemble.log', level=logging.DEBUG, format='%(name)s (%(levelname)s): %(message)s')`

([see in libE.py](https://github.com/Libensemble/libensemble/blob/2ed15a64e73b5408d1f1436fefc9c94d7d3dcbc3/libensemble/libE.py#L23))

I would speculate that this is not the desired behavior since in other parts of the code you use logger returned by `logging.getLogger(__name__ + '(' + wrkid + ')')` or `logging.getLogger(__name__ )` (see, for example, [here](https://github.com/Libensemble/libensemble/blob/2ed15a64e73b5408d1f1436fefc9c94d7d3dcbc3/libensemble/libE.py#L32)). 

Desired behaviour: libE uses it's own loggers and doesn't touch root logger and its config

Example implementation:
```
logger = logging.getLogger(__name__ )
logger.setLevel(logging.DEBUG)
fh = logging.FileHandler('ensemble.log')
formatter = logging.Formatter('%(name)s (%(levelname)s): %(message)s')
fh.setFormatter(formatter)
logger.addHandler(fh)
```

See [Logging Cookbook](https://docs.python.org/3/howto/logging-cookbook.html)

**Comment by shuds13** [comment]
What behaviour do you get as it is? From what I remember I used the root logger as it could be set for the whole application, rather than separately for each module (as it was before). The module loggers should inherit the level from the root logger.

Also, David made some changes to logging in the develop code. Are you using master or develop?

**Comment by dbindel** [comment]
This is on master -- the version on develop redirects the root logger on the call to manager_logging_config from the libE front-end functions rather than on import.  The same objection might be made for the develop version, since it is setting up the root logger rather than the libE module logger.  But since libE is the front-end routine that orchestrates everything, it seemed like we really did want this to go to the root logger.  As with the worker team setup, the intent is that a user could write their own version of one of the libE front-end routines from the pieces we provide if it makes sense to have a different type of logging.

**Comment by rsln-s** [comment]
@shuds13 what I'm experiencing is that output from other parts of my code that goes to root logger gets redirected to libensemble log file. From my point of view, after importing libensemble all my output disappears. Serves me right for using global root logger for everything, but still, it's a non-trivial thing to debug and can be a pain if one is not very familiar with Python logging.

Regarding libE being front-end routine that orchestrates everything: I quite happily use it as a (mostly) black-box optimizer. Not sure if that's a use case you endorse.

**Comment by shuds13** [comment]
Ok, I will experiment a bit with the best approach. I like being able to set the logging level in one place. Maybe there is a ways to set up a logger at the package level and allow module loggers to inherit the level. Or the module loggers could redirect to file, but we probably don't want to change root logging level for third party packages anyway. So I will look at the first approach.

**Comment by shuds13** [comment]
I have tested setting up the package logger in __init__.py. As long as libensemble is imported this will work like the root logger did. That is, all module loggers will inherit the config, unless they override it locally. An alternative could be to put it in its own module but then all modules would have to import that. That might work better if we want to provide a setloglevel API for user convenience.

E.g. In the latter case you could provide this option to change libE logging level:

from libensemble import libE_logger
libE_logger.set_log_level('INFO')

Any opinions on this?

**Comment by shuds13** [comment]
To clarify, this would work just as well in `__init__.py`.
Then you could have:

import libensemble
libensemble.set_log_level('INFO')'

**Comment by shuds13** [comment]
For next release (provisionally v0.4.1) root logging is removed and level can be set with:

from libensemble import libE_logger
libE_logger.set_level('INFO')

**Comment by shuds13** [comment]
Some modifications will need to be made when merging this into develop code.

The thing to note about loggers is the name hierarchy. So if there is a logger called libensemble, then you create a logger called libensemble.libE_worker, this will automatically inherit from libensemble. This is why the module loggers inherit from my package level logger in my branch.

I think the issue with this in the develop branch is the filters set up there have to be applied before the logger is created. So instead of creating at the package level we could create where they are now in comms/logs.py,  but instead of the root logger, we could use a logger named 'libensemble' (or if not hardcoded get from __package__.split('.')[0] - as logs.py ___package__ is libensemble.comms

ie.
    logger = logging.getLogger(__package__.split('.')[0])

instead of the root logger.

    logger = logging.getLogger()
    
I guess this means the user could not set the logging level at the start though - as in my previous examples. Unless we store what they set somewhere, and use it to initialise the loggers when they are created.

**Comment by shuds13** [comment]
I will close this and open a new issue for fixing logging in develop branch.
