### ISSUE TITLE
Remove uses of COMM_WORLD

### ISSUE THREAD

**Issue by jmlarson1** [Libensemble/libensemble#108]
libEnsemble should fully support the use of outside communicators.

**Comment by shuds13** [comment]
I have removed all uses of COMM_WORLD except to use for setting a default communicator if none is provided by the user. In this case COMM_WORLD is duplicated rather than used directly.

If a process enters libE() that is not in the communicator is returns with an exit flag of 3.

I have added updated test_mpi_comms.py and added tests test_chwirut_pounders_subcomm.py and test_chwirut_pounders_splitcomm.py to test cases where a sub-communicator is provided. In the split test, multiple copies of libEnsemble are run, each with manager and workers.
