### ISSUE TITLE
Try out gitlab CI on Theta

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#348]
Try running tests on Theta via local site gitlab CI at Argonne.

Argonne contact: Kyle Shaver

Documentation at: https://ecp-ci.gitlab.io/

**Comment by jlnav** [comment]
We've technically tried out GitLab CI on Theta. As I've stated, I'm currently unable to complete a robust workflow due to system scheduling and queue limitations that make it difficult to iterate on the workflow. I'm closing this for now, but perhaps when the Federated System is online I'll revisit this. Feel free to reopen if closing this was unnecessary.
