### ISSUE TITLE
sub node worker assignment

### ISSUE THREAD

**Issue by cchall** [Libensemble/libensemble#591]
I ran into an error trying to assign 8 workers across 3 nodes and realized that it appears that currently it appears that when trying to configure a run with `workers > nodes` that `workers % nodes` must be 0. 

This appears to come from the node assignment:
https://github.com/Libensemble/libensemble/blob/0d699f404c0a93455dbe0c25fe230c086bee7831/libensemble/resources/resources.py#L335-L338

Would it be feasible to extend this to handle cases where `workers % nodes != 0` ? 
I tried a naive implementation that extends the `global_nodelist` based on this remainder and it seemed to fix the issue for my case. Perhaps there are broader implications for such a change though?

**Comment by shuds13** [comment]
@cchall 

As you say it should be easy enough to use the mod to extend the node_list. One thing I will have to check is when workers are automatically assigned cores (this happens if you use executor.submit() without specifying your run configuration), or there is a check on the core assignment. Secondly, that it works in the [adaptive_workers](https://github.com/Libensemble/libensemble/tree/feature/adaptive_workers) branch where the generator can request different resources for each simulation.

I'm interested the reason you want an uneven distribution. Is this for different sized tasks? Or a good number for resources/worker concurrency? (I am asking this only to gauge usage scenarios, either way it should be supported).

**Comment by cchall** [comment]
@shuds13 My motivation for uneven distribution when I ran across this was trying to keep a node partially free. I have a fairly simple [custom executor setup](https://github.com/radiasoft/rsopt/blob/master/rsopt/libe_tools/executors.py) that just finds all nodes available to a user on our system. I had intended to partially fill my last node when I started a job with libensemble so I could run some other work manually in the meantime. 

More broadly I think that addressing this would alleviate a potential source of confusion. Currently if you configure a run that uses 4 workers and give a node list with a single node the run starts. However, if you change to having three nodes and the same 4 workers you now get an error. This second scenario obviously doesn't represent an efficient use of resources but it feels unintuitive to have it result in an error.

**Comment by shuds13** [comment]
@cchall

I have put in a fix in the branch feature/uneven_workers_nodes, which I should very soon pull into develop. If its working okay, it will go into release v0.7.2 which is aimed for the end of this week. Feel free to try it and see if it does what you would expect and
provide any feedback.

If the workers do not divide evenly into nodes it will put a different number of workers on the nodes rather than splitting nodes between workers. E.g. If you have 5 workers and 3 nodes you will get a 2,2,1 breakdown of workers to nodes. I will add a warning, when there is an uneven split.

**Comment by cchall** [comment]
Thanks, @shuds13!
I tried out the uneven_workers_nodes branch and it seems to do just what I need.

**Comment by jlnav** [comment]
@cchall Tentatively closing due to #600. If additional features/fixes are needed, please feel free to reopen. Thank you again for helping out!
